### ISSUE TITLE
帮忙给你提需求,哈哈

### ISSUE THREAD

**Issue by developerworks** [tothis/download#1]
如果文件大, 内存消耗是个问题

 1. 内存消耗问题
 2.下载进度跟踪

每个块估计要个 Buffer 来存,  还可以开单独的 IO 线程写文件

**Comment by developerworks** [comment]
hyper 好像支持应答体 Stream, 这样应该可以改善内存利用率

**Comment by developerworks** [comment]
https://www.reddit.com/r/rust/comments/c5q7v9/help_to_find_example_of_hyper_downloading_files/

**Comment by developerworks** [comment]
https://stackoverflow.com/questions/41444297/how-to-download-a-large-file-with-hyper-and-resume-on-error

**Comment by tothis** [comment]
感谢关注，根据你的建议我做了如下更新：
- 降低内存占用：使用流下载文件、合并文件读取时使用 `read_exact` 函数。
- 进度展示：使用 `indicatif` 库 `MultiProgress` 展示每个文件分片下载进度和合并文件进度。

**Comment by tothis** [comment]
感谢关注，根据你的建议我做了如下更新：

- 降低内存占用：使用流下载文件、合并文件读取时使用 `read_exact` 函数。
- 进度展示：使用 `indicatif` 库 `MultiProgress` 展示每个文件分片下载进度和合并文件进度。

**Comment by ThisLiLei** [comment]
感谢关注，根据你的建议我做了如下更新：

- 降低内存占用：使用流下载文件、合并文件读取每个文件分片时使用 `read_exact` 函数。
- 进度展示：使用 `indicatif` 库 `MultiProgress` 展示每个文件分片下载进度和合并文件进度。
